name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: compile
      run: c++ -Wall -Werror -Wextra -std=c++98 -pedantic *.cpp
    - name: build
      run: ./a.out

